services:
  db:
        image: postgres
        restart: always
        volumes:
            - ./db.sql:/docker-entrypoint-initdb.d/db.sql
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PWD}
            - POSTGRES_DB=${PG_DATABASE}
        ports:
            - 5432:5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_PWD}" ]
            interval: 10s
            timeout: 5s
            retries: 5

  zookeeper:
        image: bitnami/zookeeper
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
        image: bitnami/kafka
        environment:
            - ALLOW_PLAINTEXT_LISTENER=yes
        ports:
            - 9092:9092
        healthcheck:
          test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server localhost:9092"]
          interval: 10s
          timeout: 5s
          retries: 5
  api:
        build:
            context: .
            dockerfile: Dockerfile
        image: mediasoft-customer
        restart: always
        env_file:
          - .env
        depends_on:
          db:
              condition: service_healthy
          kafka:
              condition: service_healthy
        ports:
            - 8000:8000
            - 8001:8001